/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMinter1155,
  IMinter1155Interface,
} from "../../../contracts/interfaces/IMinter1155";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "ethValueSent",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "minterArguments",
        type: "bytes",
      },
    ],
    name: "requestMint",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "enum ICreatorCommands.CreatorActions",
                name: "method",
                type: "uint8",
              },
              {
                internalType: "bytes",
                name: "args",
                type: "bytes",
              },
            ],
            internalType: "struct ICreatorCommands.Command[]",
            name: "commands",
            type: "tuple[]",
          },
          {
            internalType: "uint256",
            name: "at",
            type: "uint256",
          },
        ],
        internalType: "struct ICreatorCommands.CommandSet",
        name: "commands",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMinter1155__factory {
  static readonly abi = _abi;
  static createInterface(): IMinter1155Interface {
    return new Interface(_abi) as IMinter1155Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMinter1155 {
    return new Contract(address, _abi, runner) as unknown as IMinter1155;
  }
}
