/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILimitedMintPerAddress } from "./ILimitedMintPerAddress";
export type { ILimitedMintPerAddressErrors } from "./ILimitedMintPerAddressErrors";
