/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILimitedMintPerAddressErrors,
  ILimitedMintPerAddressErrorsInterface,
} from "../../../../contracts/interfaces/ILimitedMintPerAddress.sol/ILimitedMintPerAddressErrors";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "requestedAmount",
        type: "uint256",
      },
    ],
    name: "UserExceedsMintLimit",
    type: "error",
  },
] as const;

export class ILimitedMintPerAddressErrors__factory {
  static readonly abi = _abi;
  static createInterface(): ILimitedMintPerAddressErrorsInterface {
    return new Interface(_abi) as ILimitedMintPerAddressErrorsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILimitedMintPerAddressErrors {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ILimitedMintPerAddressErrors;
  }
}
