/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IContractMetadata,
  IContractMetadataInterface,
} from "../../../../contracts/interfaces/IContractMetadata.sol/IContractMetadata";

const _abi = [
  {
    inputs: [],
    name: "contractName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "contractURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IContractMetadata__factory {
  static readonly abi = _abi;
  static createInterface(): IContractMetadataInterface {
    return new Interface(_abi) as IContractMetadataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IContractMetadata {
    return new Contract(address, _abi, runner) as unknown as IContractMetadata;
  }
}
