/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHasContractName,
  IHasContractNameInterface,
} from "../../../../contracts/interfaces/IContractMetadata.sol/IHasContractName";

const _abi = [
  {
    inputs: [],
    name: "contractName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHasContractName__factory {
  static readonly abi = _abi;
  static createInterface(): IHasContractNameInterface {
    return new Interface(_abi) as IHasContractNameInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHasContractName {
    return new Contract(address, _abi, runner) as unknown as IHasContractName;
  }
}
