/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IContractMetadata } from "./IContractMetadata";
export type { IHasContractName } from "./IHasContractName";
